language: python
python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5

before_install:
  # Use miniconda and conda packages to speed up dependency setup (principally 
  # borrowed from https://gist.github.com/dan-blanchard/7045057
  # and https://github.com/Jorge-C/ordination/blob/master/.travis.yml
  - sudo apt-get update -qq
  - sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran

  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
        MC=$HOME/miniconda2;
    else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
        MC=$HOME/miniconda3;
    fi
  - bash ./miniconda.sh -b
  - export PATH=$MC/bin:$PATH
  - hash -r
  # Update conda itself
  - conda config --set always_yes yes --set changeps1 no
  - conda update --yes conda
  # matplotlib needs a DISPLAY
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - conda create --yes -n pyblock_test python=$TRAVIS_PYTHON_VERSION nose pip numpy matplotlib pandas coverage
  - source activate pyblock_test
  - python setup.py install

script:
  - nosetests --with-coverage --cover-package=pyblock --cover-min-percentage=85 pyblock
